server:
  port: 8080 # Puerto en el que se ejecuta el gateway

spring:
  application:
    name: cloud-gateway # Nombre de la aplicación (para registro en Eureka)
  cloud:
    gateway:
      routes:
        - id: microservicio1 # Identificador único de la ruta
          uri: lb://microservicio1 # URI del microservicio (lb:// para balanceo de carga)
          predicates:
            - Path=/microservicio1/** # Predicado para las solicitudes que coinciden con este patrón
        - id: microservicio2
          uri: lb://microservicio2
          predicates:
            - Path=/microservicio2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # URL del servidor Eureka
